<?xml version="1.0"?>
<package format="3">
  <name>pils_dds_ros</name>
  <version>0.0.1</version>
  <description>Independent RTI DDS ROS2 bridge for pils topics</description>

  <maintainer email="you@example.com">you</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geographiclib</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
